import React, { useState } from "react";
import ReactMarkdown from "react-markdown";
import {
  Copy,
  Check,
  Download,
  FileCode,
  Workflow,
  Activity,
  Layers,
  ShieldCheck,
  Sparkles,
} from "lucide-react";
import { OutputSectionKey, StructuredSections } from "../types";

interface OutputViewerProps {
  sections: StructuredSections;
  rawContent?: string;
  catalog: string;
  schema: string;
}

export const OutputViewer: React.FC<OutputViewerProps> = ({
  sections,
  rawContent,
  catalog,
  schema,
}) => {
  const [activeTab, setActiveTab] = useState<OutputSectionKey | "all">("architecture");
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const tabs: {
    key: OutputSectionKey | "all";
    label: string;
    num: string;
    icon: React.ReactNode;
  }[] = [
    {
      key: "architecture",
      label: "Architecture & Strategy",
      num: "1",
      icon: <Layers className="w-4 h-4 text-amber-500" />,
    },
    {
      key: "code",
      label: "Production Code & Pipeline",
      num: "2",
      icon: <FileCode className="w-4 h-4 text-emerald-500" />,
    },
    {
      key: "workflow",
      label: "Deployment & Workflow Script",
      num: "3",
      icon: <Workflow className="w-4 h-4 text-blue-500" />,
    },
    {
      key: "monitoring",
      label: "Monitoring & Self-Healing",
      num: "4",
      icon: <Activity className="w-4 h-4 text-purple-500" />,
    },
    {
      key: "all",
      label: "Complete Deliverable",
      num: "★",
      icon: <Sparkles className="w-4 h-4 text-stone-700" />,
    },
  ];

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleDownload = (filename: string, content: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const extractCode = (markdown: string): string => {
    const match = markdown.match(/```(?:python|json|sql)?\n([\s\S]*?)```/);
    return match ? match[1] : markdown;
  };

  return (
    <div className="bg-white rounded-xl border border-stone-200 shadow-xs overflow-hidden">
      {/* Top Header & Guardrail Audit Banner */}
      <div className="bg-stone-50 border-b border-stone-200 px-5 py-3.5 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div className="flex items-center gap-3">
          <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
          <div>
            <h2 className="text-sm font-bold text-stone-900">
              Databricks Lakehouse 4-Section Deliverable
            </h2>
            <p className="text-xs text-stone-700">
              Generated by Autonomous DataOps Agent
            </p>
          </div>
        </div>

        {/* Action Buttons: Export */}
        <div className="flex items-center gap-2 flex-wrap">
          <button
            type="button"
            id="download-notebook-btn"
            onClick={() =>
              handleDownload(
                `${schema}_dlt_pipeline.py`,
                `# Databricks Notebook source\n# MAGIC %md\n# Production Pipeline for ${catalog}.${schema}\n\n` +
                  extractCode(sections.code),
                "text/x-python"
              )
            }
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-medium bg-white text-stone-700 border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
            title="Download as Databricks Python Notebook"
          >
            <Download className="w-3.5 h-3.5 text-emerald-600" />
            <span>.py Notebook</span>
          </button>

          <button
            type="button"
            id="download-workflow-btn"
            onClick={() =>
              handleDownload(
                `${schema}_workflow_job.json`,
                extractCode(sections.workflow),
                "application/json"
              )
            }
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-medium bg-white text-stone-700 border border-stone-200 hover:bg-stone-100 transition-colors cursor-pointer"
            title="Download Databricks Jobs REST API 2.1 JSON"
          >
            <Download className="w-3.5 h-3.5 text-blue-600" />
            <span>Jobs API JSON</span>
          </button>

          <button
            type="button"
            id="download-report-btn"
            onClick={() =>
              handleDownload(
                `${schema}_dataops_deliverable.md`,
                rawContent ||
                  `${sections.architecture}\n\n${sections.code}\n\n${sections.workflow}\n\n${sections.monitoring}`,
                "text/markdown"
              )
            }
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-medium bg-stone-900 text-white hover:bg-stone-800 transition-colors cursor-pointer"
            title="Download Full Markdown Deliverable"
          >
            <Download className="w-3.5 h-3.5 text-white" />
            <span>Full Report (.md)</span>
          </button>
        </div>
      </div>

      {/* Quality Guardrails Checklist Strip */}
      <div className="bg-emerald-50/70 border-b border-emerald-100 px-5 py-2 text-[11px] flex flex-wrap items-center gap-x-5 gap-y-1 text-emerald-900">
        <div className="flex items-center gap-1">
          <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" />
          <span className="font-semibold">Quality Guardrails:</span>
        </div>
        <div className="flex items-center gap-1">
          <Check className="w-3 h-3 text-emerald-600" />
          <span>Streaming Checkpoint Configured</span>
        </div>
        <div className="flex items-center gap-1">
          <Check className="w-3 h-3 text-emerald-600" />
          <span>Parameterized Catalog & Storage</span>
        </div>
        <div className="flex items-center gap-1">
          <Check className="w-3 h-3 text-emerald-600" />
          <span>DLT Quarantine Rules Implemented</span>
        </div>
        <div className="flex items-center gap-1">
          <Check className="w-3 h-3 text-emerald-600" />
          <span>Unity Catalog RBAC Respected</span>
        </div>
      </div>

      {/* 4-Section Tabs */}
      <div className="flex items-center border-b border-stone-200 bg-stone-50/50 px-3 overflow-x-auto scrollbar-none">
        {tabs.map((tab) => {
          const isActive = activeTab === tab.key;
          return (
            <button
              key={tab.key}
              id={`section-tab-${tab.key}`}
              onClick={() => setActiveTab(tab.key)}
              className={`flex items-center gap-2 py-3 px-3.5 text-xs font-medium border-b-2 whitespace-nowrap transition-colors cursor-pointer ${
                isActive
                  ? "border-red-600 text-stone-900 font-semibold bg-white"
                  : "border-transparent text-stone-600 hover:text-stone-900 hover:border-stone-300"
              }`}
            >
              <span
                className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold ${
                  isActive ? "bg-red-600 text-white" : "bg-stone-200 text-stone-700"
                }`}
              >
                {tab.num}
              </span>
              {tab.icon}
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Tab Content Display */}
      <div className="p-6">
        {activeTab === "all" ? (
          <div className="space-y-10">
            <SectionBlock
              title="1. ARCHITECTURE & STRATEGY"
              content={sections.architecture}
              badge="Design & Strategy"
              onCopy={() => handleCopy(sections.architecture, "arch")}
              isCopied={copiedKey === "arch"}
            />
            <hr className="border-stone-200" />
            <SectionBlock
              title="2. PRODUCTION CODE & PIPELINE DEFINITION"
              content={sections.code}
              badge="PySpark / DLT"
              onCopy={() => handleCopy(sections.code, "code")}
              isCopied={copiedKey === "code"}
            />
            <hr className="border-stone-200" />
            <SectionBlock
              title="3. DEPLOYMENT & WORKFLOW SCRIPT"
              content={sections.workflow}
              badge="Jobs API 2.1 JSON"
              onCopy={() => handleCopy(sections.workflow, "workflow")}
              isCopied={copiedKey === "workflow"}
            />
            <hr className="border-stone-200" />
            <SectionBlock
              title="4. MONITORING & SELF-HEALING HOOKS"
              content={sections.monitoring}
              badge="System Tables & Remediation"
              onCopy={() => handleCopy(sections.monitoring, "monitoring")}
              isCopied={copiedKey === "monitoring"}
            />
          </div>
        ) : (
          <div>
            {activeTab === "architecture" && (
              <SectionBlock
                title="1. ARCHITECTURE & STRATEGY"
                content={sections.architecture}
                badge="Medallion & Lakeflow Strategy"
                onCopy={() => handleCopy(sections.architecture, "arch")}
                isCopied={copiedKey === "arch"}
              />
            )}
            {activeTab === "code" && (
              <SectionBlock
                title="2. PRODUCTION CODE & PIPELINE DEFINITION"
                content={sections.code}
                badge="Production PySpark / DLT"
                onCopy={() => handleCopy(sections.code, "code")}
                isCopied={copiedKey === "code"}
              />
            )}
            {activeTab === "workflow" && (
              <SectionBlock
                title="3. DEPLOYMENT & WORKFLOW SCRIPT"
                content={sections.workflow}
                badge="Databricks Jobs API 2.1"
                onCopy={() => handleCopy(sections.workflow, "workflow")}
                isCopied={copiedKey === "workflow"}
              />
            )}
            {activeTab === "monitoring" && (
              <SectionBlock
                title="4. MONITORING & SELF-HEALING HOOKS"
                content={sections.monitoring}
                badge="System Tables & Remediation"
                onCopy={() => handleCopy(sections.monitoring, "monitoring")}
                isCopied={copiedKey === "monitoring"}
              />
            )}
          </div>
        )}
      </div>
    </div>
  );
};

interface SectionBlockProps {
  title: string;
  content: string;
  badge: string;
  onCopy: () => void;
  isCopied: boolean;
}

const SectionBlock: React.FC<SectionBlockProps> = ({
  title,
  content,
  badge,
  onCopy,
  isCopied,
}) => {
  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <h3 className="font-bold text-stone-900 text-base">{title}</h3>
          <span className="text-[11px] font-medium px-2 py-0.5 rounded bg-stone-100 text-stone-700 border border-stone-200">
            {badge}
          </span>
        </div>
        <button
          type="button"
          onClick={onCopy}
          className="flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-medium bg-stone-100 hover:bg-stone-200 text-stone-700 transition-colors cursor-pointer"
        >
          {isCopied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-600" />
              <span className="text-emerald-700">Copied!</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-stone-500" />
              <span>Copy Section</span>
            </>
          )}
        </button>
      </div>

      <div className="prose prose-stone max-w-none prose-pre:bg-stone-900 prose-pre:border prose-pre:border-stone-800 prose-pre:rounded-lg prose-headings:text-stone-900 prose-p:text-stone-700 prose-code:text-red-700 prose-code:bg-stone-100 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:before:content-none prose-code:after:content-none text-sm">
        <ReactMarkdown>{content}</ReactMarkdown>
      </div>
    </div>
  );
};
